runtime: nodejs
env: flex
service: vianneymobiletest

automatic_scaling:
 min_num_instances: 1
 max_num_instances: 20
 cpu_utilization:
   target_utilization: 0.75   

threadsafe: false
# resources:
#   cpu: 2
#   memory_gb: 3
# health_check:
#   enable_health_check: false

env_variables:
  #SQL_USER: usrvianneydigital
  #SQL_PASSWORD: t%rzTLw8^s;D4C(D
  #SQL_DATABASE: vianney_digital
  #INSTANCE_CONNECTION_NAME: mx-vianney-001:us-central1:db-n1-standard-8-produccion
  SQL_USER: usrvianneydigital
  SQL_PASSWORD: r-52,X.W~z8ZuBdw
  SQL_DATABASE: vianney_digital
  INSTANCE_CONNECTION_NAME: mx-vianney-001:us-central1:db-g1-small
  #NODE_ENV:  production
  
beta_settings:
  cloud_sql_instances: mx-vianney-001:us-central1:db-g1-small
  #cloud_sql_instances: mx-vianney-001:us-central1:db-n1-standard-8-produccion